openapi: 3.1.0
info:
  title: Сервис для работы с банковскими продуктами.
  description: Сервис предназначен для сотрудников банка. Он позволяет выполнить персонализированный
    подбор услуг и рекомендовать новые банковские продукты/услуги клиентам банка.
  version: 0.0.1-SNAPSHOT
servers:
- description: Development
tags:
- name: Управление системой.
  description: В данном разделе можно узнать информацию о системе и сбросить кеш.
paths:
  /rule/new:
    post:
      tags:
      - dynamic-recommendation-rule-controller
      operationId: createRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DynamicRecommendationRuleDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DynamicRecommendationRule"
  /management/clear-caches:
    post:
      tags:
      - Управление системой.
      summary: Сброс кеша рекомендаций.
      description: "Данный эндпоинт позволяет очистить все закешированные результа\
        ты, что означает обновление базы данных."
      operationId: clearCaches
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: object
  /rule:
    get:
      tags:
      - dynamic-recommendation-rule-controller
      operationId: getAllRules
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: "#/components/schemas/DynamicRecommendationRuleDto"
  /rule/stat:
    get:
      tags:
      - dynamic-recommendation-rule-controller
      operationId: getRuleStat
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: "#/components/schemas/DynamicRuleStat"
  /recommendation/{userId}:
    get:
      tags:
      - recommendation-controller
      operationId: getListOfRecommendation
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: "#/components/schemas/RecommendationObject"
  /management/info:
    get:
      tags:
      - Управление системой.
      summary: Информация о системе.
      description: Данный эндпоинт позволяет получить информацию о названии и версии
        системы.
      operationId: getServiceInfo
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InfoDTO"
  /rule/{productId}:
    delete:
      tags:
      - dynamic-recommendation-rule-controller
      operationId: deleteRule
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    DynamicRecommendationRuleDto:
      type: object
      properties:
        rule:
          type: array
          items:
            $ref: "#/components/schemas/QueryObject"
        product_id:
          type: string
        product_name:
          type: string
        product_text:
          type: string
    QueryObject:
      type: object
      properties:
        query:
          type: string
        arguments:
          type: array
          items:
            type: string
        negate:
          type: boolean
    DynamicRecommendationRule:
      type: object
      properties:
        id:
          type: string
        productName:
          type: string
        productId:
          type: string
        productText:
          type: string
        rule:
          type: string
    DynamicRuleStat:
      type: object
      properties:
        ruleId:
          type: string
        count:
          type: integer
          format: int32
    RecommendationObject:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        text:
          type: string
    InfoDTO:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
