-- liquibase formatted sql

-- changeset avdeev:1
CREATE TABLE recommendations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   UUID         NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_text TEXT,
    CONSTRAINT uk_recommendations_product_id UNIQUE (product_id) -- Если product_id уникален
);

-- changeset avdeeev:2
CREATE TABLE queries
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query              TEXT    NOT NULL,
    negate             BOOLEAN NOT NULL DEFAULT FALSE,
    recommendations_id BIGINT  NOT NULL,
    CONSTRAINT fk_queries_recommendations
        FOREIGN KEY (recommendations_id) REFERENCES recommendations (id) ON DELETE CASCADE
);

-- changeset avdeev:3
-- Таблица для аргументов (вместо TEXT[])
CREATE TABLE query_arguments
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id BIGINT NOT NULL,
    argument TEXT   NOT NULL,
    CONSTRAINT fk_query_arguments_queries
        FOREIGN KEY (query_id) REFERENCES queries (id) ON DELETE CASCADE
);

-- changeset avdeev:4
-- Таблица для сбора статистики
CREATE TABLE statistics
(
    rule_id UUID PRIMARY KEY,
    count   BIGINT NOT NULL DEFAULT 0
);

-- changeset avdeev:5
-- Таблица для телеграм-бота
CREATE TABLE telegram_user
(
    chat_id  BIGINT PRIMARY KEY,
    user_name VARCHAR(255)
);