"openapi": "3.1.0",
             "info": {
               "title": "OpenAPI definition",
               "version": "v0"
             },
             "servers": [
               {
                 "url": "http://localhost:8080",
                 "description": "Generated server url"
               }
             ],
             "paths": {
               # ===== RecommendationController =====
               "/recommendation/{userId}": {
                 "get": {
                   "tags": [
                     "recommendation-controller"
                   ],
                   "operationId": "getListOfRecommendation",
                   "parameters": [
                     {
                       "name": "userId",
                       "in": "path",
                       "required": true,
                       "schema": {
                         "type": "string",
                         "format": "uuid"
                       }
                     }
                   ],
                   "responses": {
                     "200": {
                       "description": "OK",
                       "content": {
                         "*/*": {
                           "schema": {
                             "type": "object",
                             "additionalProperties": {
                               "type": "array",
                               "items": {
                                 "$ref": "#/components/schemas/RecommendationObject"
                               }
                             }
                           }
                         }
                       }
                     }
                   }
                 }
               }
             },
  # ===== Модели данных =====
             "components": {
               "schemas": {
                 "RecommendationObject": {
                   "type": "object",
                   "properties": {
                     "id": {
                       "type": "string",
                       "format": "uuid"
                     },
                     "name": {
                       "type": "string"
                     },
                     "text": {
                       "type": "string"
                     }
                   }
                 }
               }
             }
}